In [1]:
import numpy as np


In [2]:
#SLICING IN 1D ARRAY


In [3]:
an=np.arange(10)

In [4]:
an

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
an[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
an[2:6]

array([2, 3, 4, 5])

In [7]:
an[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
an[1:8:2]

array([1, 3, 5, 7])

In [9]:
#SLICING IN 2D ARRAY

In [10]:
al=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
al

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
al[1,...]

array([4, 5, 6])

In [13]:
al[1:,...]

array([[4, 5, 6],
       [7, 8, 9]])

In [14]:
al[...,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [15]:
al[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [16]:
al[1:2]

array([[4, 5, 6]])

In [17]:
al[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [18]:
al[1:7:2]

array([[4, 5, 6]])

In [19]:
al[1:,(1,2)]

array([[5, 6],
       [8, 9]])

In [20]:
al[(1,2),2:]

array([[6],
       [9]])

In [21]:
al[1:,(2,1,0)]

array([[6, 5, 4],
       [9, 8, 7]])

In [22]:
#ACCESSING MULTIPLE VALUE(ROW) BY SPECIFYING ITS INDEX

In [23]:
al[[1,2]]

array([[4, 5, 6],
       [7, 8, 9]])